# Generated by Django 5.2.8 on 2025-11-10 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0002_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1, help_text='Round number in the tournament bracket (1=first round, 2=semifinals, etc.).')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Optional scheduled time for the match.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the match.', max_length=20)),
                ('score_a', models.PositiveIntegerField(blank=True, help_text='Goals/score for participant_a. Set when match is completed.', null=True)),
                ('score_b', models.PositiveIntegerField(blank=True, help_text='Goals/score for participant_b. Set when match is completed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_a', models.ForeignKey(help_text='First participant (player) in the match.', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_participant_a', to='tournaments.participant')),
                ('participant_b', models.ForeignKey(blank=True, help_text='Second participant (player) in the match. Can be null for byes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_participant_b', to='tournaments.participant')),
                ('tournament', models.ForeignKey(help_text='The tournament this match belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, help_text='The winning participant. Auto-determined when scores are reported.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournaments.participant')),
            ],
            options={
                'ordering': ['round_number', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('participant_a', models.F('participant_b')), _negated=True), name='no_self_match')],
            },
        ),
    ]
