# Generated by Django 5.2.8 on 2025-11-10 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('tournaments', '0002_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='participant_a',
            field=models.ForeignKey(help_text='First participant (player) in the match.', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant_b',
            field=models.ForeignKey(blank=True, help_text='Second participant (player) in the match. Can be null for byes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', help_text='Current status of the match.', max_length=20),
        ),
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.PositiveIntegerField()),
                ('score_b', models.PositiveIntegerField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='match_evidence/')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='matches.match')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('match', 'reporter', 'score_a', 'score_b'), name='unique_report_per_user_same_scores')],
            },
        ),
    ]
