# Generated by Django 5.2.8 on 2025-11-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_participant_a_alter_match_participant_b_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguestanding',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='leaguestanding',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='leaguestanding',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leaguestanding',
            name='updated_at',
        ),
    ]
