# Generated by Django 5.2.8 on 2025-11-11 02:48

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_leaguestanding_options_and_more'),
        ('tournaments', '0003_alter_participant_options_remove_tournament_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguestanding',
            options={'ordering': ['-points', '-goal_difference', '-goals_for']},
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now  # timezone-aware current time
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='leaguestanding',
            unique_together={('tournament', 'participant')},
        ),
    ]
