# Generated by Django 5.2.8 on 2025-11-11 00:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['joined_at']},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='type',
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('cup', 'Cup (Single Elimination)'), ('league', 'League (Round-Robin)')], default='cup', help_text='Cup: Single Elimination | League: Round-Robin', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('registration_open', 'Registration Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
