# Generated by Django 5.2.8 on 2026-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_participant_options_remove_tournament_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_players',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
